### ISSUE TITLE
Missing gulp-watch dependency

### ISSUE THREAD

**Issue by nathanfdunn** [iservices/build-transform#1]
This package seems to have an implicit dependency on gulp-watch. When running the transform task in a bare project, I receive an error that no 'gulp-watch' package was found. The task completed successfully after running `npm install --save-dev gulp-watch`.

**Comment by natewallace** [comment]
Nice catch.  I've moved the require statement for gulp-watch into the watch task so this error shouldn't occur anymore when running the non watch related tasks.  I've also fixed this same issue in a couple of the other build\* packages and updated the generator-iservices package to include gulp-watch as a dev dependency.
